#!/usr/bin/env bash

# bash <(curl -s https://danielsuo.com/dotfiles/tmux)

if [ -z $DOTFILES_INSTALLED ]; then
  git clone https://github.com/tmux/tmux.git
  pushd tmux
  sh autogen.sh
  mkdir -p $HOME/.local
  ./configure --prefix=$HOME/.local
  make -j
  make install
  popd
  rm -rf tmux

  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

tmux source-file ~/.tmux.conf
~/.tmux/plugins/tpm/bin/install_plugins
