#!/usr/bin/env bash

# Basics
sudo apt-get install -y \
  build-essential \
  git \
  tmux \
  vim \
  cmake \
  xclip \
  curl \
  cmake

# Monitoring
sudo apt-get install -y \
  htop \
  iotop \
  sysstat \
  linux-tools-common \
  linux-tools-generic
