#!/usr/bin/env bash

# bash <(curl -s http://danielsuo.com/dotfiles/vim)

if [ -z $DOTFILES_INSTALLED ]; then
  git clone https://github.com/vim/vim.git
  pushd vim
  make distclean
  ./configure --with-features=huge \
              --enable-pythoninterp \
              --prefix=$HOME/.local
  make -j
  make install
  popd
  rm -rf vim

  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim +PlugInstall +qall
