#!/usr/bin/env bash

if [ -z $DOTFILES_INSTALLED ]; then

  if [ "$OSTYPE" == "linux-gnu" ]; then
    git clone https://github.com/neovim/neovim.git
    pushd neovim

    # Make dependencies
    mkdir .deps
    pushd .deps
    cmake ../third-party
    make
    # make install
    popd

    mkdir build
    pushd build
    cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local ..
    make
    make install
    popd
    popd
    rm -rf neovim
  fi

  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  git clone https://github.com/powerline/fonts
  pushd fonts
  ./install.sh
  popd
  rm -rf fonts
fi

if [ -x "$(command -v pip2)" ]; then
  pip2 install neovim --user --upgrade
fi
if [ -x "$(command -v pip3)" ]; then
  pip3 install neovim --user --upgrade
fi

pip install neovim --user --upgrade
nvim +PlugInstall +UpdateRemotePlugins +qall
