#!/usr/bin/env bash

# bash <(curl -s http://danielsuo.com/dotfiles/vim)

git clone https://github.com/vim/vim.git
cd vim
make distclean
./configure --with-features=huge --prefix=$HOME/.local
make -j
make install

# curl http://danielsuo.com/dotfiles/vimrc.txt -o ~/.vimrc
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
