name: Daniel Suo
description: Scientific progress goes 'boink'
url: http://www.danielsuo.com

permalink: /:year/:month/:day/:title
category_paginate: 5
categories:
-
  - 'main'
  - '/index.html'
-
  - 'beliefs'
  - '/projects/beliefs/index.md'
-
  - 'five'
  - '/projects/five/index.md'

changefreq: 'daily'

redcarpet:
  extensions: ['smart']

kramdown:
  smart_quotes:  lsquo,rsquo,ldquo,rdquo

include:
- .gitignore
- .nojekyll

exclude:
- Gemfile*
- bin
- .bowerrc
- .git
