name: Daniel Suo
description: Scientific progress goes 'boink'
url: http://www.danielsuo.com

category_paginate: 5
categories:
- 
  - 'main'
  - '/index.html'
-
  - 'beliefs'
  - '/projects/beliefs/index.md'
-
  - 'five'
  - '/projects/five/index.md'

kramdown:
  smart_quotes:  lsquo,rsquo,ldquo,rdquo

include:
- .gitignore