#!/usr/bin/env bash

if [ ! -f ~/.dotfiles ]; then
  # Leave a mark
  echo "export DOTFILES_HOME=$(pwd)" >> ~/.dotfiles
  echo 'export PATH=~/.local/bin:$PATH' >> ~/.dotfiles
fi

# Source environment variables
source ~/.dotfiles

if [ ! `which git` ]; then
  echo 'ERROR: Requires at least git. Come on, really?'
  exit
fi

function downloader_wget {
  wget -O $2 $1 -q
}

function downloader_curl {
  curl -o $2 $1 -s
}

function runner_wget {
  wget -O - $1 -q | bash
}

function runner_curl {
  bash <(curl -s $1)
}

if [ `which wget` ]; then
  downloader=downloader_wget
  runner=runner_wget
else
  downloader=downloader_curl
  runner=runner_curl
fi

SUO="https://danielsuo.com/dotfiles"

echo
$downloader $SUO/profile.txt $HOME/.profile
$downloader $SUO/bashrc.txt $HOME/.bashrc
$downloader $SUO/gitconfig.txt $HOME/.gitconfig
$downloader $SUO/vimrc.txt $HOME/.vimrc
$downloader $SUO/tmux.conf $HOME/.tmux.conf

source ~/.profile

$runner $SUO/tmux
$runner $SUO/vim

if [ -z $DOTFILES_INSTALLED ]; then
  echo "export DOTFILES_INSTALLED=TRUE" >> ~/.dotfiles
fi
