#!/bin/sh

git pull origin dev
git add .
git commit -m "$1"
git push origin dev

jekyll build

git checkout master
git pull origin master
ls | grep -v "_site\|node_modules" | xargs rm -rf
cp -R _site/ .
git add .
git commit -m "$1"
git push origin master

git checkout dev
